### ISSUE TITLE
Tab Administration is not showing up

### ISSUE THREAD

**Issue by problemwolf** [inrae/sturwild#9]
Can't figure out where to change the APPLI_code and totp_identifier. There is no tab Administration.
https://sturwild.$LOCALDOM/declarationList ->
`You do not have the necessary rights to perform this function`

https://sturwild.$LOCALDOM/administration ->
`You do not have the necessary rights to perform this function`

https://sturwild.$LOCALDOM/admin -> 404

**Comment by equinton** [comment]
You must change the .env file with:
database.default.searchpath=sturwild,sturwildgacl,public

(I've seen the ticket #8 where you put the fix, it's just for close this ticket. The new release is now ok)
